/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/babel.config`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/areamanager/adetails`; params?: Router.UnknownInputParams; } | { pathname: `/areamanager/alist`; params?: Router.UnknownInputParams; } | { pathname: `/areamanager/alogin`; params?: Router.UnknownInputParams; } | { pathname: `/components/LogoHeader`; params?: Router.UnknownInputParams; } | { pathname: `/engineer/details`; params?: Router.UnknownInputParams; } | { pathname: `/engineer/list`; params?: Router.UnknownInputParams; } | { pathname: `/engineer/login`; params?: Router.UnknownInputParams; } | { pathname: `/src/config/cloudinary.config`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/PDFUploadScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/cloudinaryUpload`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/complaintReportTemplate`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/documentGenerator`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/submitComplaintUpdate`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/babel.config`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/types`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/areamanager/adetails`; params?: Router.UnknownOutputParams; } | { pathname: `/areamanager/alist`; params?: Router.UnknownOutputParams; } | { pathname: `/areamanager/alogin`; params?: Router.UnknownOutputParams; } | { pathname: `/components/LogoHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/engineer/details`; params?: Router.UnknownOutputParams; } | { pathname: `/engineer/list`; params?: Router.UnknownOutputParams; } | { pathname: `/engineer/login`; params?: Router.UnknownOutputParams; } | { pathname: `/src/config/cloudinary.config`; params?: Router.UnknownOutputParams; } | { pathname: `/src/screens/PDFUploadScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/cloudinaryUpload`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/complaintReportTemplate`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/documentGenerator`; params?: Router.UnknownOutputParams; } | { pathname: `/src/utils/submitComplaintUpdate`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/babel.config${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/types${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/areamanager/adetails${`?${string}` | `#${string}` | ''}` | `/areamanager/alist${`?${string}` | `#${string}` | ''}` | `/areamanager/alogin${`?${string}` | `#${string}` | ''}` | `/components/LogoHeader${`?${string}` | `#${string}` | ''}` | `/engineer/details${`?${string}` | `#${string}` | ''}` | `/engineer/list${`?${string}` | `#${string}` | ''}` | `/engineer/login${`?${string}` | `#${string}` | ''}` | `/src/config/cloudinary.config${`?${string}` | `#${string}` | ''}` | `/src/screens/PDFUploadScreen${`?${string}` | `#${string}` | ''}` | `/src/utils/cloudinaryUpload${`?${string}` | `#${string}` | ''}` | `/src/utils/complaintReportTemplate${`?${string}` | `#${string}` | ''}` | `/src/utils/documentGenerator${`?${string}` | `#${string}` | ''}` | `/src/utils/submitComplaintUpdate${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/babel.config`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/areamanager/adetails`; params?: Router.UnknownInputParams; } | { pathname: `/areamanager/alist`; params?: Router.UnknownInputParams; } | { pathname: `/areamanager/alogin`; params?: Router.UnknownInputParams; } | { pathname: `/components/LogoHeader`; params?: Router.UnknownInputParams; } | { pathname: `/engineer/details`; params?: Router.UnknownInputParams; } | { pathname: `/engineer/list`; params?: Router.UnknownInputParams; } | { pathname: `/engineer/login`; params?: Router.UnknownInputParams; } | { pathname: `/src/config/cloudinary.config`; params?: Router.UnknownInputParams; } | { pathname: `/src/screens/PDFUploadScreen`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/cloudinaryUpload`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/complaintReportTemplate`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/documentGenerator`; params?: Router.UnknownInputParams; } | { pathname: `/src/utils/submitComplaintUpdate`; params?: Router.UnknownInputParams; };
    }
  }
}
